name: Metrics

on:
  schedule: [{cron: "0 0 * * 1"}] # Chaque lundi
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: valentin-dev
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_lines: yes
          plugin_traffic: yes
